apiVersion: v1
description: High Performance Object Storage
name: minio
version: 5.1.0
appVersion: RELEASE.2024-03-03T17-50-39Z
keywords:
  - minio
  - storage
  - object-storage
  - s3
  - cluster
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
- https://github.com/minio/minio
maintainers:
- name: MinIO, Inc
  email: dev@minio.io
