name: VulnCheck
on:
  pull_request:
    branches:
    - master

jobs:
  vulncheck:
    name: Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
          check-latest: true
      - name: Check for vulnerabilities
        uses: kmulvey/govulncheck-action@v1.0.0
